package dev.zwazel.springintro.security.auth;

import dev.zwazel.springintro.security.auth.payload.AuthenticationRequest;
import dev.zwazel.springintro.security.auth.payload.AuthenticationResponse;
import dev.zwazel.springintro.security.auth.payload.RegisterRequest;
import dev.zwazel.springintro.security.jwt.JwtService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseCookie;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST Controller for authentication operations.
 *
 * <h2>Purpose</h2>
 * This controller exposes three REST endpoints that handle user authentication flows:
 * user registration, login (authentication), and logout. It acts as the gateway
 * between HTTP clients and the authentication service layer.
 *
 * <h2>Security Architecture</h2>
 * <ul>
 *   <li><b>Stateless Authentication</b>: No server-side sessions. Each request carries
 *       its own JWT token in a secure HTTP cookie or Authorization header.</li>
 *   <li><b>JWT Tokens</b>: Generated by {@link AuthenticationService} and wrapped in
 *       secure HTTP cookies by {@link JwtService}. Use {@link HttpHeaders#SET_COOKIE}
 *       to instruct the client to store the token in a cookie for automatic inclusion
 *       in subsequent requests.</li>
 *   <li><b>Secure Cookie Attributes</b>: All JWT cookies are HTTP-only (not accessible
 *       to JavaScript), secure (HTTPS-only), and SameSite=Strict (prevents CSRF attacks).</li>
 *   <li><b>Request Validation</b>: Uses Jakarta Bean Validation ({@code @Valid} annotation)
 *       to validate incoming requests before passing them to the service layer. Invalid
 *       requests are rejected with HTTP 400 Bad Request.</li>
 * </ul>
 *
 * <h2>Data Flow</h2>
 * <pre>
 * CLIENT REQUEST
 *    ↓
 * AuthenticationController (HTTP endpoint)
 *    ↓
 * AuthenticationService (business logic - credential validation, user creation)
 *    ↓
 * JwtService (token generation and cookie wrapping)
 *    ↓
 * ResponseEntity with SET-COOKIE header
 *    ↓
 * CLIENT (stores JWT in cookie, includes in future requests)
 * </pre>
 *
 * <h2>Endpoints Overview</h2>
 * <ul>
 *   <li><b>POST /api/v1/auth/register</b>: Creates new user and returns JWT</li>
 *   <li><b>POST /api/v1/auth/authenticate</b>: Verifies credentials and returns JWT</li>
 *   <li><b>POST /api/v1/auth/logout</b>: Invalidates JWT cookie on client</li>
 * </ul>
 *
 * @see AuthenticationService - Handles register() and authenticate() business logic
 * @see JwtService - Responsible for token generation and cookie management
 * @see AuthenticationRequest - DTO for login credentials
 * @see RegisterRequest - DTO for user registration details
 * @see AuthenticationResponse - DTO for authentication response (contains generated token)
 */
@RestController
@RequestMapping("/api/v1/auth")
@RequiredArgsConstructor
public class AuthenticationController {

    private final AuthenticationService authenticationService;
    private final JwtService jwtService;

    /**
     * Registers a new user and returns a JWT token.
     *
     * <h3>Endpoint</h3>
     * {@code POST /api/v1/auth/register}
     *
     * <h3>Process Flow</h3>
     * <ol>
     *   <li>Client sends registration request with email, password (and optional details)</li>
     *   <li>@Valid annotation triggers validation of RegisterRequest (checks constraints
     *       like password strength, email format, required fields)</li>
     *   <li>AuthenticationService.register() creates new User with bcrypt-hashed password
     *       and stores in database</li>
     *   <li>Service generates JWT token using JwtService</li>
     *   <li>JwtService wraps token in a secure HTTP cookie</li>
     *   <li>Response includes SET-COOKIE header instructing client to store the cookie</li>
     * </ol>
     *
     * <h3>Security Considerations</h3>
     * <ul>
     *   <li><b>Request Validation</b>: @Valid ensures password meets strength requirements
     *       (see StrongPassword annotation) and email is valid format</li>
     *   <li><b>Password Hashing</b>: AuthenticationService uses bcrypt (never stored plain text)</li>
     *   <li><b>Cookie Security</b>: JWT placed in HTTP-only cookie, cannot be accessed by
     *       JavaScript (prevents XSS token theft)</li>
     *   <li><b>Duplicate Accounts</b>: If email already exists, service throws exception
     *       (check application behavior for error response details)</li>
     * </ul>
     *
     * @param request {@link RegisterRequest} containing email and password.
     *                Must satisfy validation constraints (see request class for details).
     *                Example: { "email": "user@example.com", "password": "Str0ng!Pass123" }
     * @return {@link ResponseEntity} with status 200 OK, containing:
     *         - Response body: {@link AuthenticationResponse} with generated access token
     *         - SET-COOKIE header: JWT token in secure HTTP-only cookie
     * @throws org.springframework.security.core.AuthenticationException if validation fails
     *         or user creation fails
     *
     * @see RegisterRequest - Details on password validation rules
     * @see AuthenticationResponse - Format of response body
     * @see JwtService#generateJwtCookie(String) - Creates the secure cookie
     */
    @PostMapping("/register")
    public ResponseEntity<AuthenticationResponse> register(@Valid @RequestBody RegisterRequest request) {
        // STEP 1: Delegate user creation and initial credential validation to AuthenticationService
        // This service handles password hashing (bcrypt) and database persistence
        AuthenticationResponse authenticationResponse = authenticationService.register(request);

        // STEP 2: Wrap the generated JWT token in a secure HTTP cookie
        // The cookie has attributes: httpOnly (cannot be accessed by JS), secure (HTTPS only),
        // sameSite=Strict (prevents CSRF), and expires in 24 hours (see application.properties)
        ResponseCookie jwtCookie = jwtService.generateJwtCookie(authenticationResponse.getAccessToken());

        // STEP 3: Build response with SET-COOKIE header
        // SET-COOKIE tells the browser to store the JWT token in the cookie jar
        return ResponseEntity.ok()
                .header(HttpHeaders.SET_COOKIE, jwtCookie.toString())
                .body(authenticationResponse);
    }

    /**
     * Authenticates a user and returns a JWT token.
     *
     * <h3>Endpoint</h3>
     * {@code POST /api/v1/auth/authenticate}
     *
     * <h3>Process Flow</h3>
     * <ol>
     *   <li>Client sends credentials (email/username and password)</li>
     *   <li>AuthenticationService.authenticate() delegates to Spring's AuthenticationManager</li>
     *   <li>AuthenticationManager loads user via UserDetailsService and verifies password
     *       using bcrypt comparison</li>
     *   <li>If credentials valid, JwtService generates JWT token containing user claims</li>
     *   <li>Service wraps token in secure HTTP cookie</li>
     *   <li>Response includes SET-COOKIE header and returns token in body</li>
     * </ol>
     *
     * <h3>Security Considerations</h3>
     * <ul>
     *   <li><b>Password Verification</b>: bcrypt comparison (timing-safe) prevents
     *       brute-force attacks and rainbow table attacks</li>
     *   <li><b>User Loading</b>: AuthenticationManager loads authorities (Role + Privileges)
     *       from database, then encodes in JWT</li>
     *   <li><b>Token Claims</b>: JWT includes subject (username/email), issuedAt, expiration,
     *       and encoded authorities for authorization checks</li>
     *   <li><b>Stateless</b>: Server stores no session state; token is self-contained proof
     *       of authentication</li>
     * </ul>
     *
     * @param request {@link AuthenticationRequest} containing email and password
     *                Example: { "email": "user@example.com", "password": "Str0ng!Pass123" }
     * @return {@link ResponseEntity} with status 200 OK, containing:
     *         - Response body: {@link AuthenticationResponse} with access token
     *         - SET-COOKIE header: JWT token in secure HTTP-only cookie
     * @throws org.springframework.security.core.AuthenticationException if credentials
     *         are invalid or user not found
     *
     * @see AuthenticationRequest - DTO structure
     * @see AuthenticationResponse - DTO structure
     * @see AuthenticationService#authenticate(AuthenticationRequest) - Credential validation logic
     * @see JwtService#generateJwtCookie(String) - Creates the secure cookie
     */
    @PostMapping("/authenticate")
    public ResponseEntity<AuthenticationResponse> authenticate(@RequestBody AuthenticationRequest request) {
        // STEP 1: Validate credentials against database user
        // AuthenticationService delegates to Spring's AuthenticationManager, which:
        // - Loads User from database
        // - Compares request password with stored bcrypt hash
        // - Throws exception if credentials invalid
        AuthenticationResponse authenticationResponse = authenticationService.authenticate(request);

        // STEP 2: Generate new JWT token containing user's authorities
        // Token is valid for 15 minutes (see jwt.expiration in application.properties)
        ResponseCookie jwtCookie = jwtService.generateJwtCookie(authenticationResponse.getAccessToken());

        // STEP 3: Return token in both body and cookie
        // Browser stores cookie automatically; response body also contains token
        // Some clients may prefer Authorization header over cookies
        return ResponseEntity.ok()
                .header(HttpHeaders.SET_COOKIE, jwtCookie.toString())
                .body(authenticationResponse);
    }

    /**
     * Logs out a user by invalidating their JWT cookie.
     *
     * <h3>Endpoint</h3>
     * {@code POST /api/v1/auth/logout}
     *
     * <h3>Process Flow</h3>
     * <ol>
     *   <li>Client initiates logout with an authenticated request</li>
     *   <li>JwtService creates a "clean" JWT cookie with maxAge=0 (immediate expiration)</li>
     *   <li>Response includes SET-COOKIE header with the expired cookie</li>
     *   <li>Browser receives Set-Cookie with maxAge=0 and deletes the stored JWT cookie</li>
     *   <li>Subsequent requests without JWT are treated as unauthenticated</li>
     * </ol>
     *
     * <h3>Security Considerations</h3>
     * <ul>
     *   <li><b>Cookie Deletion</b>: Browser-side deletion via maxAge=0. The token itself
     *       remains valid until expiration (15 min by default), so compromised tokens from
     *       cache might still be usable. This is acceptable for teaching scenarios; production
     *       systems use token blacklisting (database of revoked tokens) for stronger security.</li>
     *   <li><b>No Database Lookup</b>: Logout is instant and requires no database access
     *       (stateless design benefit)</li>
     *   <li><b>Client-Side Cleanup</b>: If client stores token in localStorage/sessionStorage,
     *       client code should also clear it (not handled by this endpoint)</li>
     *   <li><b>Authentication Required</b>: Endpoint is accessible to requesters with valid
     *       JWT. Unauthenticated logout requests are rejected by JwtAuthenticationFilter.</li>
     * </ul>
     *
     * <h3>Why Logout Exists</h3>
     * JWT tokens are stateless and self-contained (server doesn't track them). True "server-side
     * logout" is not possible without token blacklisting. This endpoint provides cookie-based
     * logout for browser-based clients by instructing the browser to delete the stored cookie.
     *
     * @return {@link ResponseEntity} with status 200 OK and no body, containing:
     *         - SET-COOKIE header: Expired JWT cookie (maxAge=0)
     *
     * @see JwtService#getCleanJwtCookie() - Creates cookie with maxAge=0
     */
    @PostMapping("/logout")
    public ResponseEntity<Void> logout() {
        // STEP 1: Create a "clean" JWT cookie with maxAge=0
        // maxAge=0 tells browser to immediately delete the cookie
        ResponseCookie jwtCookie = jwtService.getCleanJwtCookie();

        // STEP 2: Return empty response with SET-COOKIE header (with maxAge=0)
        // Browser deletes the stored JWT cookie on receiving this response
        // Future requests will not include the JWT token in cookies
        return ResponseEntity.ok()
                .header(HttpHeaders.SET_COOKIE, jwtCookie.toString())
                .build();
    }
}